server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lesson7
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true