server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop
    username: root
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  thymeleaf:
    enabled: true
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
